### ISSUE TITLE
mmon terminates with error

### ISSUE THREAD

**Issue by michaelkrone** [sebhildebrandt/mmon#1]
Hello @sebhildebrandt 

When I try to start mmon, it just terminates with the message `Terminated with error ...`

The error thrown is:
```
TypeError: Cannot read property '1' of null
    at /usr/local/lib/node_modules/mmon/node_modules/systeminformation/lib/filesystem.js:587:64
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/mmon/node_modules/systeminformation/lib/filesystem.js:577:21
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```
My system: `
Linux 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by michaelkrone** [comment]
Closing this since the behaviour was caused by a dependent package.
